name: nginx module build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download nginx
      run: |
        wget https://nginx.org/download/nginx-1.20.0.tar.gz
        tar -xzvf nginx-1.20.0.tar.gz
      working-directory: ./../
    - name: configure
      run: ./configure --with-compat --add-dynamic-module=$GITHUB_WORKSPACE
      working-directory: ./../nginx-1.20.0
    - name: make
      run: make modules
      working-directory: ./../nginx-1.20.0
    - name: save
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ../nginx-1.20.0/objs/ngx_http_cache_purge_module.so