name: nginx module build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download nginx
      run: |
        wget https://nginx.org/download/nginx-1.20.0.tar.gz
        tar -xzvf nginx-1.20.0.tar.gz
      working-directory: ./../
    - name: configure
      run: ./configure --with-compat --add-dynamic-module=$GITHUB_WORKSPACE
      working-directory: ./../nginx-1.20.0
    - name: make
      run: make modules
      working-directory: ./../nginx-1.20.0
    - name: copy
      run: cp ../nginx-1.20.0/objs/ngx_http_cache_purge_module.so ./
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          README.md
          LICENSE
          ngx_http_cache_purge_module.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
